use customer_behavior;
select * from customer_beh;

rename table customer to customers;

-- Q1 - total revenue generated by male vs female customers 

select sum(purchase_amount), gender from customers group by gender;

-- Q2 - which customer uses discount and still spenf more than  the average purchase amount

select customer_id, purchase_amount from customers where  discount_applied = "Yes" and purchase_amount > ( select avg(purchase_amount) from customers);

-- Q3 - Which are the top 5 products with highest average review rating 

select item_purchased , avg(review_rating) as avg_rating from customers group by item_purchased order by avg_rating desc limit 5;

-- Q4 - compare the average purchases amounts between stadard and express shipping 

select avg(purchase_amount), shipping_type from customers where shipping_type in ("Express", "Standard" ) group by shipping_type ; 

-- Q5 do subscribed customers spend more, compare average and total revenue between subscribes and non subscribers.alter

select count(customer_id),avg(purchase_amount), sum(purchase_amount),subscription_status from customers group by subscription_status ;

-- Q6 Which 5 products have highest percentage of purchases with discount applied

select item_purchased, 100 * sum(case when discount_applied = "yes" then 1 else 0 end) / count(*) as high from customers  group by item_purchased order by high desc limit 5;

-- Q7  segment customers into new, returning and loyal based on their total number of previous purchases nd shoe the count of each segment 

select  case when previous_purchases = 1  then "New" when previous_purchases <= 10 then "Returning" else "Loyal" end as segment, count(previous_purchases)  from customers group by segment;

-- Q8 what are the top 3 most purchased products within each group

select dense_rank() over(partition by category  order by count(*) desc),  category from customers group by category;

with item_counts as ( select category,item_purchased, count(customer_id) as total_orders, row_number() over(partition by category order by count(customer_id)) as item_rank 
from customers group by category, item_purchased) 
select item_rank, category, item_purchased, total_orders from item_counts where item_rank <= 3;

-- Q9 are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe


select count(customer_id), subscription_status from customers where previous_purchases > 5 group by subscription_status;

-- Q10 What is the revenue contribution of each group 

select age_group  ,sum(purchase_amount) from customers group by age_group order by sum(purchase_amount) desc;